# -*- coding: utf-8 -*-
"""DressMe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16h1vjX1VC-3yjtrUFmEwdzDqhdaODmJB
"""

import tensorflow as tf
from tensorflow import keras
import numpy as np
model = keras.Sequential()
input_layer = keras.layers.Dense(4, input_shape=[4], activation='relu')
model.add(input_layer)

output_layer = keras.layers.Dense(1, activation='relu')
model.add(output_layer)

gd = tf.train.GradientDescentOptimizer(0.001)

model.compile(optimizer=gd,loss='mean_squared_error')
# Data input
x = tf.Variable(np.genfromtxt('x.csv',delimiter=','))
y = tf.Variable(np.genfromtxt('y.csv',delimiter=','))


# testing data set
test = tf.Variable([[1,9,1,2]])

init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    model.fit(x, y, epochs=2000, steps_per_epoch=10) #to increase training time
    model.save_weights('dressMe_model.h5')
    results = model.predict(test, verbose=1, steps=1)
    print(results)